config/routes.rb
Rails.application.routes.draw do
    
  resources :homilies
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :users do
    member do
      get :following, :followers
    end
  end
    
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  get 'help'     => 'static_pages#help'    
  get 'about'    => 'static_pages#about'
  get 'contact'  => 'static_pages#contact'
  get 'signup'   => 'users#new'
  get 'login'    => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'=> 'sessions#destroy'
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts,      only: [:create, :destroy]
  

end
    
    

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
    @micropost = current_user.microposts.build
    @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  This is the about page.
</p>

app/views/static_pages/help.html.erb
<%= provide(:title, "Help") %>
<h1>Deacon App</h1>
<p>This is the help page </p>

app/views/static_pages/home.html.erb
<br>
<br>
<% if logged_in? %>
<div class = "menu">
 <span> <%= link_to 'Posts', current_user %> </span>
<span> <%= link_to  'Homilies', new_homily_path %> </span>
</div>
    <div class="">
        
        <aside class = "col-md-4">
            <section class="user_info">
                <%= render 'shared/user_info' %>
            </section>
            

            <section class="stats">
                <%= render 'shared/stats' %>
            </section>
            <section class = "micropost_form">
                <%= render 'shared/micropost_form' %>
            </section>
            
        </aside>
            <div clas="col-md-8">
                <h3> Micropost Feed </h3>
                <%= render 'shared/feed' %>
            </div>
        </div>
        <% else %>
 <div class="center jumbotron">
    <h1>Welcome to the Deacon App</h1>
    <p>
      This is the home page for the Deacons of the Diocese of Venice
    
      
    </p>
<div class = "home title" >  <%= link_to image_tag("page_logo.png",alt: "Diocese of Venice"), id: "logo" %> </div>
    <br>
    <br>
    <%= link_to "Sign up now!", signup_path, class: "home_btn btn btn-large btn-primary" %>
  </div>

  
<% end %>