config/routes.rb
Rails.application.routes.draw do
    
  resources :homilies
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :users do
    member do
      get :following, :followers
    end
  end
    
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  get 'help'     => 'static_pages#help'    
  get 'about'    => 'static_pages#about'
  get 'contact'  => 'static_pages#contact'
  get 'signup'   => 'users#new'
  get 'login'    => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'=> 'sessions#destroy'
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts,      only: [:create, :destroy]
  

end
    
    

app/models/homily.rb
class Homily < ApplicationRecord
  belongs_to :user
end

app/controllers/homilies_controller.rb
class HomiliesController < ApplicationController
  before_action :set_homily, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:create, :destroy]
   
     
  # GET /homilies
  # GET /homilies.json
  def index
    @homilies = Homily.all
  end

  # GET /homilies/1
  # GET /homilies/1.json
  def show
  end

  # GET /homilies/new
  def new
    @homily = Homily.new
  end

  # GET /homilies/1/edit
  def edit
  end

  # POST /homilies
  # POST /homilies.json
  def create
    @homily = current_user.homilies.build(homily_params)

    respond_to do |format|
      if @homily.save
        format.html { redirect_to @homily, notice: 'Homily was successfully created.' }
        format.json { render :show, status: :created, location: @homily }
      else
        format.html { render :new }
        format.json { render json: @homily.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homilies/1
  # PATCH/PUT /homilies/1.json
  def update
    respond_to do |format|
      if @homily.update(homily_params)
        
        format.html { redirect_to @homily, notice: 'Homily was successfully updated.' }
        format.json { render :show, status: :ok, location: @homily }
      else
        format.html { render :edit }
        format.json { render json: @homily.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homilies/1
  # DELETE /homilies/1.json
  def destroy
    @homily.destroy
    respond_to do |format|
      format.html { redirect_to homilies_url, notice: 'Homily was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homily
      
      @homily = current_user.homilies.find_by(id: params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homily_params
      params.require(:homily).permit(:date, :subject, :week, :time, :cycle, 
      :first_reading_book, :first_reading_chapter, :first_reading_verse, 
      :second_reading_book, :second_reading_chapter, :second_reading_verse,
      :gospel_book, :gospel_chapter, :gospel_verse, :homily_text, :user_id)
    end
end

app/helpers/homilies_helper.rb
module HomiliesHelper
end

app/views/homilies/_form.html.erb
<%= form_for(homily) do |f| %>
  <% if homily.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(homily.errors.count, "error") %> prohibited this homily from being saved:</h2>

      <ul>
      <% homily.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject %>
  </div>

  <div class="field">
    <%= f.label :week %>
    <%= f.text_field :week %>
  </div>

  <div class="field">
    <%= f.label :time %>
    <%= f.text_field :time %>
  </div>

  <div class="field">
    <%= f.label :cycle %>
    <%= f.text_field :cycle %>
  </div>

  <div class="field">
    <%= f.label :first_reading_book %>
    <%= f.text_field :first_reading_book %>
  </div>

  <div class="field">
    <%= f.label :first_reading_chapter %>
    <%= f.text_field :first_reading_chapter %>
  </div>

  <div class="field">
    <%= f.label :first_reading_verse %>
    <%= f.text_field :first_reading_verse %>
  </div>

  <div class="field">
    <%= f.label :second_reading_book %>
    <%= f.text_field :second_reading_book %>
  </div>

  <div class="field">
    <%= f.label :second_reading_chapter %>
    <%= f.text_field :second_reading_chapter %>
  </div>

  <div class="field">
    <%= f.label :second_reading_verse %>
    <%= f.text_field :second_reading_verse %>
  </div>

  <div class="field">
    <%= f.label :gospel_book %>
    <%= f.text_field :gospel_book %>
  </div>

  <div class="field">
    <%= f.label :gospel_chapter %>
    <%= f.text_field :gospel_chapter %>
  </div>

  <div class="field">
    <%= f.label :gospel_verse %>
    <%= f.text_field :gospel_verse %>
  </div>

  <div class="field">
    <%= f.label :homily_text %>
    <%= f.text_area :homily_text %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homilies/edit.html.erb
<h1>Editing Homily</h1>

<%= render 'form', homily: @homily %>

<%= link_to 'Show', @homily %> |
<%= link_to 'Back', homilies_path %>

app/views/homilies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homilies</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Subject</th>
      <th>Week</th>
      <th>Time</th>
      <th>Cycle</th>
      <th>Gospel</th>
      
      
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homilies.each do |homily| %>
      <tr>
        <td><%= homily.date %></td>
        <td><%= homily.subject %></td>
        <td><%= homily.week %></td>
        <td><%= homily.time %></td>
        <td><%= homily.cycle %></td>
        <td><%= homily.gospel_book %></td>
        
        
        
        <td><%= link_to 'Show', homily %></td>
        <td><%= link_to 'Edit', edit_homily_path(homily) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class = "homily">
<%= link_to '+ New Homily', new_homily_path %>
</div>

app/views/homilies/new.html.erb
<h1>New Homily</h1>

<%= render 'form', homily: @homily %>

<%= link_to 'Back', homilies_path %>

app/views/homilies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @homily.date %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @homily.subject %>
</p>

<p>
  <strong>Week:</strong>
  <%= @homily.week %>
</p>

<p>
  <strong>Time:</strong>
  <%= @homily.time %>
</p>

<p>
  <strong>Cycle:</strong>
  <%= @homily.cycle %>
</p>

<p>
  <strong>First reading book:</strong>
  <%= @homily.first_reading_book %>
</p>

<p>
  <strong>First reading chapter:</strong>
  <%= @homily.first_reading_chapter %>
</p>

<p>
  <strong>First reading verse:</strong>
  <%= @homily.first_reading_verse %>
</p>

<p>
  <strong>Second reading book:</strong>
  <%= @homily.second_reading_book %>
</p>

<p>
  <strong>Second reading chapter:</strong>
  <%= @homily.second_reading_chapter %>
</p>

<p>
  <strong>Second reading verse:</strong>
  <%= @homily.second_reading_verse %>
</p>

<p>
  <strong>Gospel book:</strong>
  <%= @homily.gospel_book %>
</p>

<p>
  <strong>Gospel chapter:</strong>
  <%= @homily.gospel_chapter %>
</p>

<p>
  <strong>Gospel verse:</strong>
  <%= @homily.gospel_verse %>
</p>

<p>
  <strong>Homily text:</strong>
  <%= @homily.homily_text %>
</p>

<p>
  <strong>User:</strong>
  <%= @homily.user %>
</p>

<%= link_to 'Edit', edit_homily_path(@homily) %> |
<td><%= link_to 'Destroy', homily, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<%= link_to 'Back', homilies_path %>