config/routes.rb
Rails.application.routes.draw do
    
  resources :homilies
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :users do
    member do
      get :following, :followers
    end
  end
    
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  get 'help'     => 'static_pages#help'    
  get 'about'    => 'static_pages#about'
  get 'contact'  => 'static_pages#contact'
  get 'signup'   => 'users#new'
  get 'login'    => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'=> 'sessions#destroy'
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts,      only: [:create, :destroy]
  

end
    
    

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :homilies, dependent: :destroy
  has_one  :info, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
  mount_uploader :picture, PictureUploader
  has_secure_password

  validates :password, length: { minimum: 6 }, allow_blank: true

  # Returns the hash digest of the given string.
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute( :remember_digest, User.digest( remember_token ) )
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Activates an account.
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # Sends password email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end


  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Defines a proto-feed.
  
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                    OR user_id = :user_id", user_id: id)
  end
  
  # Follows a user.
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

  private

  def downcase_email
    # Converts email to all lower-case.
    self.email = email.downcase
  end

  def create_activation_digest
    # Create the token and digest.
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,
                only: [ :index, :edit, :update , :destroy,
                        :following, :followers]
  #before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:update, :edit , :destroy]

  def index
    @users = User.paginate(page: params[:page ], :per_page => 12)
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page ], :per_page => 10)
  end

  def new
    @user = User.new
  end

   def create
    @user = User.new(user_params)
    if @user.save
      # Handle a successful save.
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
   end

  def edit
    @user = User.find(params[:id])
  end

  def update
     @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
   def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
   end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,
         :first_name, :last_name,     :middle_name, :date_of_birth,  :street_address, 
         :city,     :state,          :zip_code,   :phone,    :cell_phone,   :wife_name, 
         :wife_date_of_birth,       :wedding_anniversary,      :diocese_of_ordination, 
        :ordination_date,     :diocese_of_incardination,      :incardination_date, 
         :military_service,      :military_branch,     :military_period, :military_years,      :military_rank,      :faculties,   :preaching,     :status, 
     :employer,   :employer_address,     :secondary_address, :secondary_city,      :secondary_state, :secondary_zip, 
        :secondary_phone,      :assignment,      :assignment_location, :assignment_pastor,    :emergency_contact_name,     :emergency_contract_phone,
         :highschool,  :under_graduate,      :graduate,      :doctorate,      :field_of_study,
         :prior_employment_description,  :prior_diaconate_ministry,   :picture )
    end
    
    # Before filters
    
    
   
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
    <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
    <% else %>
        <%= render 'follow' %>
    <% end %>
   </div>
   <% end %>

app/views/users/_form.html.erb
<div class= "sign_up_body">
  <%= image_tag @user.picture.url if @user.picture? %>
    <%= form_for @user, :html => {:class => 'form-inline', :role => 'form'}  do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class = "avatar">
     
      
 </div>
      <div class = "form-group Picture ">
          Profile Picture
      <%=  f.file_field :picture, accept: 'image/jpeg.image/gif.image/png', class: 'form control' %>
    </div>
    <br>
    
       <div class = "form-group">
      <%= f.label :user_name %>
      <%= f.text_field :name, class: 'form control' %>
      </div>
      
      <div class = "form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form control' %>
      </div>
      
      <br>
      <div class = "form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form control' %>
      </div>
      
      <div class = "form-group">
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form control' %>
      </div>
      <br>

       
       
       <br>
       
     <div class = "form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form control' %>
  </div>

    <div class = "form-group">
    <%= f.label :middle_initial %>
    <%= f.text_field :middle_name, class: 'short_form' %>
     </div>
     
     <div class = "form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form control' %>
    </div>

    <div class = "form-group">
    <%= f.label :date_of_birth %>
    <%= f.text_field :date_of_birth, placeholder: "mm/dd/yyyy", class: 'form control' %>
    </div>
     
    <br>
    <div class = "form-group">
    <%= f.label :street_address %>
    <%= f.text_field :street_address, class: 'long_form' %>
    </div>

     <div class = "form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: 'form control' %>
    </div>

    <div class = "form-group">  
    <%= f.label :state %>
    <%= f.text_field :state, class: 'short_form' %>
    </div>

        <div class = "form-group">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code, class: 'short_form2' %>
</div>
<br>

        <div class = "form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: 'form control' %>
  </div>

        <div class = "form-group">
    <%= f.label :cell_phone %>
    <%= f.text_field :cell_phone, class: 'form control' %>
  </div>
<br>
     <div class = "form-group">
    <%= f.label :wife_name %>
    <%= f.text_field :wife_name, class: 'form control' %>
 </div>

    <div class = "form-group">
    <%= f.label :wife_date_of_birth %>
    <%= f.text_field :wife_date_of_birth, placeholder: "mm/dd/yyyy", class: 'form control' %>
 </div>

     <div class = "form-group">
    <%= f.label :wedding_anniversary %>
    <%= f.text_field :wedding_anniversary, placeholder: "mm/dd/yyyy", class: 'form control' %>
</div>
<br>
     <div class = "form-group">
    <%= f.label :diocese_of_ordination %>
    <%= f.text_field :diocese_of_ordination, class: 'form control' %>
 </div>

   <div class = "form-group">
    <%= f.label :ordination_date %>
    <%= f.text_field :ordination_date, placeholder: "mm/dd/yyyy", class: 'form control' %>
  </div>

   <div class = "form-group">
    <%= f.label :diocese_of_incardination %>
    <%= f.text_field :diocese_of_incardination, class: 'form control' %>
  </div>

     <div class = "form-group">
    <%= f.label :incardination_date %>
    <%= f.text_field :incardination_date, placeholder: "mm/dd/yyyy", class: 'form control' %>
  </div>


    <div class = "form-group">
    <%= f.label :military_service %>
    <%= f.check_box :military_service, class: 'form control' %>
</div>

     <div class = "form-group">
    <%= f.label :military_branch %>
    <%= f.text_field :military_branch, class: 'form control' %>
 </div>

     <div class = "form-group">
    <%= f.label :military_period %>
    <%= f.text_field :military_period, class: 'form control' %>
  </div>
  
   <div class = "form-group">
    <%= f.label :military_years %>
    <%= f.text_field :military_years, class: 'form control' %>
</div>
  
     <div class = "form-group">
    <%= f.label :military_rank %>
    <%= f.text_field :military_rank, class: 'form control' %>
  </div>
<br>

   <div class = "form-group">
    <%= f.label :faculties %>
    <%= f.check_box :faculties, class: 'form control' %>
  </div>

     <div class = "form-group">
    <%= f.label :preaching %>
    <%= f.check_box :preaching, class: 'form control' %>
  </div>

     <div class = "form-group">
    <%= f.label :status  %>
    <%= f.text_field :status, class: 'form control'  %>
  </div>
<br>

     <div class = "form-group">
    <%= f.label :employer %>
    <%= f.text_field :employer, class: 'form control' %>
 </div>

   <div class = "form-group">
    <%= f.label :employer_address %>
    <%= f.text_field :employer_address, class: 'long_form' %>
 </div>
<br>

    <div class = "form-group">
    <%= f.label :my_other_address %>
    <%= f.text_field :secondary_address, class: 'long_form' %>
 </div>

   <div class = "form-group">
    <%= f.label :my_other_city %>
    <%= f.text_field :secondary_city, class: 'form control' %>
</div>

  
     <div class = "form-group">
    <%= f.label :other_state %>
    <%= f.text_field :secondary_state, class: 'short_form' %>
    </div>

     <div class = "form-group">
    <%= f.label :other_zip %>
    <%= f.text_field :secondary_zip, class: 'short_form2' %>
    </div>

     <div class = "form-group">
    <%= f.label :other_phone %>
    <%= f.text_field :secondary_phone, class: 'form control' %>
    </div>
<br>
    <div class = "form-group">
    <%= f.label :assignment %>
    <%= f.text_field :assignment, class: 'form control' %>
    </div>

     <div class = "form-group">
    <%= f.label :assignment_location %>
    <%= f.text_field :assignment_location, class: 'form control' %>
    </div>

    <div class = "form-group">
    <%= f.label :assignment_pastor %>
    <%= f.text_field :assignment_pastor, class: 'form control' %>
</div>
<br>
    <div class = "form-group">
    <%= f.label :emergency_contact_name %>
    <%= f.text_field :emergency_contact_name, class: 'form control' %>
 </div>

     <div class = "form-group">
    <%= f.label :emergency_contract_phone %>
    <%= f.text_field :emergency_contract_phone, class: 'form control' %>
  </div>
   <br>
      <div class = "form-group">
    <%= f.label :highschool %>
    <%= f.check_box :highschool, class: 'form control' %>
 </div> 

     <div class = "form-group">
    <%= f.label :under_graduate %>
    <%= f.check_box :under_graduate, class: 'form control' %>
 </div>
 
    <div class = "form-group">
    <%= f.label :graduate %>
    <%= f.check_box :graduate, class: 'form control' %>
  </div>
  
   <div class = "form-group">
    <%= f.label :doctorate %>
    <%= f.check_box :doctorate, class: 'form control' %>
  </div>
        
     <div class = "form-group">
    <%= f.label :field_of_study_or_special_skills %>
    <%= f.text_field :field_of_study, class: 'form control' %>
   </div>
  
  <br>
   <div class = "form-group">
     <%= f.text_area :prior_employment_description , placeholder: "Prior employment experience/ certifications ", class: 'area' %>
  </div>
      <br> 
    <div class = "form-group">
      <%= f.text_area :prior_diaconate_ministry, placeholder: "Prior Diaconate Experience", class: 'area' %>
    </div>
         
         <br>
         
         
         
         
         <br>
         
       

      <%= f.submit "submit", class: "signup btn btn-large btn-primary" %>
    <% end %>
    </div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<td>        <%=  user.last_name %>  </td>
<td>         <%=  user.first_name %> </td>
<td>         <%=  user.email %>   </td>
 <td>        <%=  user.cell_phone %>  </td>
 <td>        <%=  user.phone %>  </td>
        
        <% if current_user.admin? && !current_user?(user) %>
            <td>  |  <%= link_to "delete", user, method: :delete,
                                      data: { confirm: "Delete this user?"} %> </td>
        <% end %>
                                      
    

app/views/users/about.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
        <% render 'shared/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form control' %>

      <%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>

<div class="container center_div">
  <div class= "sign_up_title">
       
      <h1 >Edit Profile</h1>
      </div>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

</div>

app/views/users/index.html.erb
<h1> Deacons</h1>


<table>
   <%= will_paginate %>
  <thead>
    <tr>
      <th> Pic </th>
      <th>Last Name</th>
      <th>First Name</th>
      <th>Cell Phone</th>
      <th>Email</th>
      <th>Parish</th>
      <th></th>
      <th></th>
     
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr class="<%= cycle('even', 'odd') %>">
              <td><%= image_tag user.picture.url if user.picture? %> </td>
        <td><%= user.last_name %></td>
        <td><%= user.first_name %></td>
        <td><%= user.cell_phone %></td>
        <td><%= user.email %></td>
        <td> <%= user.assignment %> </td>
        
        
     
       <td ><%= link_to 'Posts', user_path(user) %></td>
      
        <td> <%= link_to "View_or_Edit", edit_user_path(user) %> </td>
        <% end %>
        
      </tr>
    
      
  </tbody>

</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>




 <div class="container center_div">
  <div class= "sign_up_title">
       
      <h1 >Sign up</h1>
      </div>
      
      <%= render 'form', user: @user %>
  </div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row posts">
<aside class="col-md-4">
    <section class= "user_info">
<h1>
     <%= image_tag @user.picture.url if @user.picture? %>
<%= @user.name %>

</h1>
</section>
<section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
    <h3> Microposts (<%= @user.microposts.count %>) </h3>
    <%= will_paginate @microposts %>
    <ol class="microposts">
         
        <%= render @microposts %>
    </ol>
    
    <% end %>
  </div>
</div>

app/views/users/show_details.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= image_tag @user.picture.url if @user.picture? %>
        <%= @user.name %>
         "last_name"   
    
 
       "first_name"

     "middle_name"
               "email"
    t.string   "date_of_birth"
    t.string   "street_address"
    t.string   "city"
    t.string   "state"
    t.string   "zip_code"
    t.string   "phone"
    t.string   "cell_phone"
    t.string   "wife_name"
    t.string   "wife_date_of_birth"
    t.string   "wedding_anniversary"
    t.string   "diocese_of_ordination"
    t.string   "ordination_date"
    t.string   "diocese_of_incardination"
    t.string   "incardination_date"
    t.string   "military_service"
    t.string   "military_branch"
    t.string   "military_period"
    t.string   "military_years"
    t.string   "military_rank"
    t.string   "faculties"
    t.string   "preaching"
    t.string   "status"
    t.string   "employer"
    t.string   "employer_address"
    t.string   "secondary_address"
    t.string   "secondary_city"
    t.string   "secondary_state"
    t.string   "secondary_zip"
    t.string   "secondary_phone"
    t.string   "assignment"
    t.string   "assignment_location"
    t.string   "assignment_pastor"
    t.string   "emergency_contact_name"
    t.string   "emergency_contract_phone"
    t.string   "highschool"
    t.string   "under_graduate"
    t.string   "graduate"
    t.string   "doctorate"
    t.string   "field_of_study"
    t.string   "prior_employment_description"
    t.string   "prior_diaconate_ministry"
    t.string   "picture"
        
        
        
        
        
        
        
        
        
        
      </h1>
    </section>
  </aside>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">

      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
            <ul>
          <% @users.each do |user| %>
          <li>
            <%= link_to user.name %>
            </li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>