config/routes.rb
Rails.application.routes.draw do
    
  resources :homilies
  get 'password_resets/new'

  get 'password_resets/edit'

  resources :users do
    member do
      get :following, :followers
    end
  end
    
  resources :sessions,      only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root to: 'static_pages#home'
  get 'help'     => 'static_pages#help'    
  get 'about'    => 'static_pages#about'
  get 'contact'  => 'static_pages#contact'
  get 'signup'   => 'users#new'
  get 'login'    => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'=> 'sessions#destroy'
  
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts,      only: [:create, :destroy]
  

end
    
    

app/views/layouts/_footer.html.erb
<footer class="footer">
  
    <p> Deacon App </p>
    
  
  <nav>
    <ul>
      <li><%= link_to "About",   "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
     
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  
    <div class="container">
      <%= link_to image_tag("deacon-logo.gif", alt: "Deacon logo"), id: "logo" %>
    
      
      <nav>
        <div class = "title" >  <%= link_to image_tag("page_logo.png",alt: "Diocese of Venice"), id: "logo" %> </div>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if logged_in? %>
            <li> <%= link_to "Users", users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class = "dropdown-menu">
              <li> <%= link_to "Posts", current_user %> </li>
              <li> <%= link_to "Profile", edit_user_path(current_user) %> </li>
              <li> <%= link_to "Settings", edit_user_path(current_user) %> </li>
                <% if current_user.admin? && !current_user?(@user) %>
              <li> <%= link_to "Deacons",   users_path %> </li>
                  <% end %>  
              <li class= "divider"> </li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
              </ul>
              </li>
             <% else %>
               <li><%= link_to "Log in", login_path %></li>
               <% end %>
        </ul>
      </nav>
    </div>
  
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%= yield(:title) %> | Deacon App </title>
   

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= csrf_meta_tags %>
     <%= render 'layouts/shim' %>
  </head>

  <body>
       <%= render 'layouts/header' %>
    <div class= "container">
        <% flash.each do |message_type, message| %>
        <div class= "alert alert-<%= message_type %>"> <%= message %> </div>
        <% end %>
    <%= yield %>
       
       </div>
       <%= render 'layouts/footer' %>
  </body>
</html>